name: Deploy on push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Generate dataset
        run: npm run generate:data
      - run: npm run build
      - name: Commit dataset
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/events.json scripts/geocode-cache.json || true
          git diff --staged --quiet || git commit -m "chore(data): push build dataset"
          git push || true
      - name: Deploy to Vercel
        run: npx vercel --prod --token "$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

