name: Nightly Scrape + Deploy

on:
  schedule:
    - cron: '0 6 * * *' # 6 AM UTC daily
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - name: Generate dataset
        run: npm run generate:data
      - name: Validate dataset
        run: npm run validate:dataset public/data/events.json || true
      - name: Commit dataset
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/events.json scripts/geocode-cache.json || true
          git diff --staged --quiet || git commit -m "chore(data): nightly refresh"
          git push || true
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ -n "$VERCEL_TOKEN" ]; then
            npx vercel --token "$VERCEL_TOKEN" --prod --yes
          else
            echo "No VERCEL_TOKEN secret set; skipping deploy"
          fi
