name: Scrape, build and deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Generate dataset
        run: npm run generate:data

      - name: Validate dataset
        run: npm run validate:dataset public/data/events.json || true

      - name: Commit dataset
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/events.json scripts/geocode-cache.json || true
          git diff --staged --quiet || git commit -m "chore(data): update events"
          git push || true

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ -n "$VERCEL_TOKEN" ]; then
            npx vercel --token "$VERCEL_TOKEN" --prod --yes
          else
            echo "No VERCEL_TOKEN set; skipping deploy"
          fi


